# Generated by Django 4.2.11 on 2024-05-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Avatar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "src",
                    models.ImageField(
                        default="app_profiles/avatars/default.png",
                        upload_to="app_profiles/avatars/user_avatars/",
                        verbose_name="Link",
                    ),
                ),
                ("alt", models.CharField(max_length=128, verbose_name="Description")),
            ],
            options={
                "verbose_name": "Avatar",
                "verbose_name_plural": "Avatars",
            },
        ),
    ]
