# Generated by Django 4.2.11 on 2024-05-17 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_alter_profile_options_profile_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avatar",
            name="src",
            field=models.ImageField(
                default="app_profiles/default.jpg",
                upload_to="app_profiles/",
                verbose_name="Link",
            ),
        ),
    ]
