# Generated by Django 4.2.11 on 2024-06-07 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0012_alter_review_rate"),
        ("profiles", "0005_alter_avatar_src"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                (
                    "deliveryType",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("free", "free"),
                            ("express", "express"),
                            ("ordinary", "ordinary"),
                        ],
                        default="free",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "paymentType",
                    models.CharField(
                        blank=True,
                        choices=[("online", "online"), ("offline", "offline")],
                        default="online",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "totalCost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Total price",
                    ),
                ),
                ("status", models.CharField(max_length=50, verbose_name="Status")),
                ("city", models.CharField(max_length=50, verbose_name="City")),
                ("address", models.CharField(max_length=250, verbose_name="Address")),
                (
                    "products",
                    models.ManyToManyField(
                        related_name="orders", to="products.product"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="profiles.profile",
                        verbose_name="Profile",
                    ),
                ),
            ],
        ),
    ]
