# Generated by Django 4.2.11 on 2024-05-17 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_remove_categoryimage_category_category_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to="products.categoryimage",
                verbose_name="CategoryImage",
            ),
        ),
        migrations.AlterField(
            model_name="categoryimage",
            name="src",
            field=models.ImageField(
                blank=True, null=True, upload_to="app_products/categories/"
            ),
        ),
    ]
