# Generated by Django 4.2.11 on 2024-05-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_product_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="src",
            field=models.ImageField(upload_to="app_products/products/"),
        ),
    ]
