# Generated by Django 4.2.11 on 2024-05-17 05:56

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_productimage_src"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="src",
            field=models.ImageField(upload_to=products.models.product_image_path),
        ),
    ]
