# Generated by Django 4.2.11 on 2024-05-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_productimage_src"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=5, default=0, max_digits=10, verbose_name="Price"
            ),
        ),
    ]
