# Generated by Django 4.2.11 on 2024-05-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Price",
            ),
        ),
    ]
