# Generated by Django 4.2.11 on 2024-05-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rate",
            field=models.IntegerField(default=1, verbose_name="Rate"),
        ),
    ]
